[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm --prefix backend-typescript ci --include=dev"]

[phases.build]
cmds = ["npm --prefix backend-typescript run build"]

[start]
cmd = "npm --prefix backend-typescript start"
